---
# blocks don't support loop
- name: "Pull the source RPMs"
  include_tasks: ../mock/srpmpull.yml
  vars:
    source_mode: srpm
    srpm_url: "{{ reg_item }}"
  tags:
    - mock
    - git_pull
...
