---
# blocks don't support loop
- name: "Pull the git RPM data"
  include_tasks: mock_srpmpull.yml
  vars:
    source_mode: git
    git_url: "{{ chain_git_url }}/{{ reg_item }}.git"
    source_package_name: "{{ reg_item }}"
  tags:
    - mock
    - git_pull
...
