---
# cleanup mock remains
- name: Remove deployed scripts and configs
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg"
    - "/home/{{ mock_builder }}/mock-wrapper.sh"
    - "/home/{{ mock_builder }}/{{ source_name }}"
    - "/home/{{ mock_builder }}/rpmbuild"
    - "/home/{{ mock_builder }}/module"
    - "/var/tmp/.build_in_progress"
  tags:
    - mock
    - cleanup
...
