---
################################################################################
# transfer wrapper, copy the files to where they need to be. another task will
# take care of the repo generation if it's required.
- name: "Transfer build block"
  block:
    - name: "Transfer single build"
      include_tasks: "transfer/single.yml"
      when: not mock_chain|bool
      tags:
        - transfer

    - name: "Transfer chain build"
      include_tasks: "transfer/chain.yml"
      when: mock_chain|bool
      tags:
        - transfer
  tags:
    - transfer
    - mock
...
