---
# tasks for a mock build - only run under the mock tag
# This imports necessary vars and runs needed checks before continuing
- name: "Import el{{ major }} vars and perform checks"
  include_tasks: wrapper/mock/vars.yml
  tags:
    - mock

# This ensures that mock is setup properly, including the user, installed
# packages, and various directories we'll be using.
- name: "Ensure that {{ mock_builder }} is setup properly"
  include_tasks: wrapper/mock/setup.yml
  tags:
    - mock
    - module

# This section is for regular (non-module) builds
- name: Regular Build Block
  block:
    # This is currently a workaround for chains
    - name: "Set a new var for the source name"
      set_fact:
        source_package_name: "{{ source_name }}"

    # Chain related tasks are off-loaded here
    - name: "Import chain tasks"
      include_tasks: wrapper/chain.yml
      when:
        - mock_chain|bool

    # Source RPM data is pulled here, whether git or url
    - name: "Pull the source RPM data"
      include_tasks: wrapper/mock/srpmpull.yml
      when:
        - not mock_chain|bool
      tags:
        - mock
        - git_pull
        - srpm_pull

    # Here we check if the builds were done before and skip them if so
    - name: "Verify if the build or builds were ever done"
      include_tasks: wrapper/verify.yml
      tags:
        - mock
        - git_pull
        - srpm_pull

    # Build tasks are performed
    - name: "Perform the build tasks"
      include_tasks: wrapper/mock/build.yml
      tags:
        - mock

    # Finished packages and logs are transfered to their respective spots
    - name: "Transfer RPMs"
      include_tasks: wrapper/transfer.yml
      tags:
        - mock
        - transfer

    # If we are creating repos, we'll do so here. Scratch builds are skipped.
    - name: "Import createrepo tasks"
      include_tasks: wrapper/repo/createrepo.yml
      when:
        - generate_repo|bool or bootstrap|bool
        - not scratch_build|bool
      tags:
        - mock
        - createrepo
  when:
    - not module_mode|bool

# Below is for module related builds
# These operations have been offloaded into module.yaml
- name: Module Build Block
  block:
    - name: Import Module Tasks
      include_tasks: module.yml
      tags:
        - mock
        - module
        - createrepo
  when:
    - module_mode|bool

# This performs the cleanup, regardless of build type
- name: "Cleanup"
  include_tasks: wrapper/mock/cleanup.yml
  tags:
    - mock
    - module
    - cleanup
...
